### ISSUE TITLE
Creating a shadow page changes the template persistently

### ISSUE THREAD

**Issue by danrot** [sulu/sulu-standard#289]
If you have created a page in a certain language, and create a shadow page from it, it takes the template from the page the shadow shows to, and overrides it. This change is still applying after removing the shadow from the page.

**Comment by dantleech** [comment]
This would seem to be a frontend issue, after saving the PHPCR node seems to be in a valid state:

![phpcr_shadpw](https://cloud.githubusercontent.com/assets/530801/13772516/88e0c202-ea8c-11e5-81da-bdd1f738f4d0.png)

However, after reloading the page and resaving the template is updated.

#### Problem

The problem is that the UI is loading all of the shadow data and when save is called it sends all of the shadow data back to the server, where the server dutifully updates the template.

#### Solution

We should only send fields which are required in forms, here we should not send the "structure type" (`template`) field.
