### ISSUE TITLE
Offer a docker or vagrant image

### ISSUE THREAD

**Issue by danrot** [sulu/sulu-standard#543]
It would be nice for other developers to have a ready-to-run package of docker or vagrant, to get in touch with Sulu really quickly.

Without digging deeper into it I would prefer docker, since it seems to be the more modern and faster alternative. AFAIK it is also not relying on NFS, which causes quite a lot of problems when using vagrant.

**Comment by Swader** [comment]
Paraphrasing discussion from Twitter:

- docker is more a deployment environment than dev environment, and has a steeper learning curve. It also enforces an app architecture that not everyone might be looking for. It also has flimsy support on Windows and as such is not a true cross-platform solution. It's a good option to have, but it's only good alongside Vagrant if you really want to provide good cross platform dev boxes.
- vagrant box already handled with [Homestead Improved](http://www.sitepoint.com/quick-tip-get-homestead-vagrant-vm-running/) - just using `type: symfony-sulu` under `sites` handles things and configures the internal Nginx for hosting Sulu. Tutorial coming soon.

The problems with NFS are caused by massive recursive reads due to Symfony apps having hundreds of packages installed by default as bare minimum. There's no way around that other than either inventing a different file sharing approach for VMs or moving the `vagrant` folder out of the synced area, as per https://github.com/sulu-io/sulu-standard/issues/542

Anyway, Vagrant tutorial coming soon, would be cool if you could link to it and we'll make sure it's kept up to date.

**Comment by Clindbergh** [comment]
> docker is more a deployment environment than dev environment, and has a steeper learning curve

Is this still considered to be the case nowadays?

>  It also has flimsy support on Windows and as such is not a true cross-platform solution 

I am assuming this is much better now.

> Anyway, Vagrant tutorial coming soon, would be cool if you could link to it and we'll make sure it's kept up to date.

Is this Vagrant tutorial now available (@Swader) ?

**Comment by Swader** [comment]
No I stopped working on all this shortly after but docker is indeed better on windows now, especially with WSL2. I still don't use it though, it enforces a terrible architecture I'm not a fan of.

**Comment by Clindbergh** [comment]
Perhaps a **[lando](https://lando.dev/) [recipe](https://docs.lando.dev/config/recipes.html)** is the preferred way.
---

> it enforces a terrible architecture 

@Swader would be curious to hear why you think so?

**Comment by Swader** [comment]
It slaps a layer of faux networking on top of your forcibly decoupled architecture that you then have to parkour around to get the pieces to talk to one another and makes building and modifying source code a nightmare, increasing dependency on the image-building team and centralizing development further.

**Comment by alexander-schranz** [comment]
@Clindbergh there is a [sulu-docker](https://github.com/sulu/sulu-docker) for development but currently we are not using it in the core team not sure if it is still in use by the team of @TomKeur.

We mostly go in development with the way that we have PHP installed locally and only have services like mysql, elasticsearch and so in docker. This is from our side the best option as docker will never be as fast as having it installed locally.

For having only service in docker see for example the [sulu-demo docker-compose](https://github.com/sulu/sulu-demo/blob/master/docker-compose.yml) file.

There are also other tools like [ddev](https://github.com/drud/ddev) by @rfay, but I'm not familiar with that one.

**Comment by alexander-schranz** [comment]
@Clindbergh @rfay is also in our slack channel you can register for it [here](https://sulu.io/services-and-support#chat).

**Comment by Clindbergh** [comment]
@alexander-schranz Thanks, the links as well as your own experience is definitely very helpful.

With sulu-docker in existence, perhaps the issue could be closed.

**Comment by rfay** [comment]
Plenty of Sulu users love [DDEV-Local])(https://ddev.readthedocs.io/en/stable/). It's easy to set up, wraps docker very nicely, works on all platforms, macOS, Linux,. Windows, Windows WSL2.

There's a #ddev channel in Sulu slack, happy to chat there. 

There are some docs and a starter setup by @nevercodealone at https://github.com/drud/awesome-ddev#sulu-documentation
