### ISSUE TITLE
Decide recommendation for installing/updating Sulu

### ISSUE THREAD

**Issue by webmozart** [sulu/sulu-standard#633]
At the moment, some people install Sulu by cloning Sulu Standard. They update their application by pulling from the original repo and resolving any conflicts. (approach A)

Others bootstrap their application by taking Sulu Standard, but getting rid of the relationship to the original repository. The snapshot of Sulu Standard at the time of creating the project is the first commit in such a repository. Updates are performed by checking out diffs between individual Sulu versions and applying them manually. (approach B)

Both approaches have benefits and downsides. Let's try to enumerate them:
##### Advantages
- Relatively easy to perform updates
##### Disadvantages
- Impossible to distinguish recommended/optional from mandatory changes when updating
- The development of Sulu Standard is constrained by BC considerations. For example, it cannot be easily simplified (https://github.com/sulu-io/sulu/issues/2078) in order to provide a better experience for starters.
##### Advantages
- Sulu Standard can be optimized in order to provide the best experience for newcomers
- Sulu Standard can be changed. It could always reflect the current best practice for _starting_ a new project.
##### Disadvantages
- Updates become more complicated since diffs need to be created and applied manually. This could be mitigated by providing a `sulu:upgrade` command that performs some changes automatically.

Both styles have different implications on the changes we can do to this repository with regard to BC:
- https://github.com/sulu-io/sulu/issues/2078 (and others linked in there)
- https://github.com/sulu-io/sulu-standard/issues/458
- https://github.com/sulu-io/sulu-standard/issues/546

I think we should make a decision here.

**Comment by webmozart** [comment]
This issue is blocking the other issues linked in the description.

**Comment by chirimoya** [comment]
@c00n84 @sabinebaer @alexander-schranz need your feedback please.

**Comment by alexander-schranz** [comment]
# Approach B: Sulu Standard as project template

Its mostly more work but the right way to go because currently in the project all commits from sulu-standard which should not be their and make the repo bigger as it should. When go with A the git history of the project is not usable because of all sulu-standard commits. B will have a good git history for the project and right versioning. Also the variant A handling with git tags is not awesome because the tags are not remote specific if you fetch them. So it could be that you git checkout 1.1 of your project and get 1.1 of sulu-standard instead. I'm definitely for B.

**Comment by danrot** [comment]
I'd also go for approach B. Might also be a bit biased here, since I am mainly working on maintaining the project :smile: But I think it's not too much of additional work, as I've already described in https://github.com/sulu-io/sulu/pull/2077#issuecomment-193680367. When looking at the changes done in sulu-standard I am even more convinced by that statement, since most of it is just moving configuration and/or some code style fixes suggested by StyleCI.

Maybe we can be even more sensible regarding the configuration, and make even more use of features like the `PrependExtension`s. Some configuration options absolutely have to be defined, otherwise Sulu is not working at all. I guess it would be a good idea to have these configurations managed by `PrependExtension`s. However, I don't have to much experience with that kind of stuff, it is just an idea :-)

**Comment by adsc** [comment]
Approach B seems to make more sense. I don't think a more involved upgrade process is a big obstacle, as long as it works and is well documented.

**Comment by sabinebaer** [comment]
Approach B sounds more reasonable but the time needed to do an update should still be as low as possible. This should be ok if Sulu Standard is reduced to a minimum, e.g. with #593 or by checking if all dependencies in composer.json are needed.

Using Approach B would also solve the following problem: Updating when using the ClientWebsiteBundle with the default theme is not that easy as the update can destroy the layout (of course, but this is maybe not obvious for new Sulu developers).

What happens to Sulu translations, e.g. web/admin/translations/sulu.de.json? Only downloading and replacing them could lead to missing translations for additional bundles (at the moment there are merge conflicts in this case which make it obvious that something has to be done). IMO the translate bundle should be included in the dev part of the Kernel in Sulu Standard anyway and using the build command for translations should be the recommended way when updating Sulu.

**Comment by danrot** [comment]
@sabinebaer I've already added the translation bundle in https://github.com/sulu-io/sulu-standard/commit/5a05f9b03c2d6ffe62d5eacd5410e62c1fdae8f4, so this should be like that in the next release. But you are right, having the correct translations is a little bit more complicated and might be easily forgotten (a single missing translation might stay hidden for some time...). So this is definitely a downside of this method. Would also make the installation a little bit more complicated, and that's what we are actually trying to reduce here...

**Comment by sagikazarmark** [comment]
Well, I am coming in as the devil's advocate :stuck_out_tongue: : I am in favor of Approach A.

Both solutions have downsides, and the lack of update possibilities is a major one IMO.

Let me start with an example: here are my standard repositories, all of them branching from the main symfony one:

https://github.com/sagikazarmark/symfony-standard
https://github.com/sagikazarmark/platform-standard
https://github.com/sagikazarmark/sylius-standard
https://github.com/sagikazarmark/sonata-standard

And of course:
https://github.com/sagikazarmark/sulu-standard

So I am speaking from experience :smile: 

This approach let me easily updating any projects. For example: added docker in the symfony one. I easily merged the symfony repo in each other, added a few things and now I have docker in each of them. And this is true for the actual projects, not just for boilerplates.

From my point of view, the downsides are:

- If you update regularly, lots of conflicts to be resolved (although doing this for some time now and I didn't have any which couldn't be resolved in a few minutes)
- Lots of merge commits (which is kinda good for reviewing what happened)
- Hard to keep BC (as mentioned by @alexander-schranz, but instead of tags, I would use separate branches. They don't have to be preserved locally, can simply be removed and pulled in from upstream if necessary)

Of course there are some things which I am not completely aware of, so these might be disadvantages as well:

- For example: I removed the translations from VC and added them to a build script. Is it a good/bad idea?
- Is the ClientWebsiteBundle the commonly used bundle the people should use?

Another idea: You could have a sandbox repo (updated from the standard) which contains everything for a working demo (and this should actually be the used demo). And there could be the standard version which is purely a project template (but used as a base for sandbox). This way you could separate optional/mandatory changes and keep the standard "clean". (Of course it must be documented step by step how to achieve the sandbox state based on the standard)

Final thought: I am not saying Approach A is better, I am saying it worked for me better for actual projects. For a project standard repo in general, option B might work better.

**Comment by alexander-schranz** [comment]
> For example: I removed the translations from VC and added them to a build script. Is it a good/bad idea?

I like the idea that the `json` translations are in a build script and not part of the `sulu-standard` git repository. We can add it to the composer postScript to generate the files. What you think @danrot @wachterjohannes

**Comment by sagikazarmark** [comment]
> We can add it to the composer postScript to generate the files.

Excellent idea. Although it is probably hard to guess what languages should be generated. Or just generate all? Also, translation generation requires db connection, doesn't it?

**Comment by danrot** [comment]
There is already a job doing that, callable with `app/console sulu:build translations`, which simply builds all translations for Sulu. And I would favor every single step removing built files from any repository we have :wink:

**Comment by sagikazarmark** [comment]
Where can I find it? It is not defined here: https://github.com/sulu-io/sulu-standard/blob/develop/app/config/admin/sulu.yml#L28

**Comment by wachterjohannes** [comment]
in the config there are only composed build-targets the translations build target is defined in a class https://github.com/wachterjohannes/sulu/blob/master/src/Sulu/Bundle/TranslateBundle/Build/TranslationBuilder.php

**Comment by wachterjohannes** [comment]
when you call `app/console sulu:build` you get a list of available targets and the dependencies.

**Comment by sagikazarmark** [comment]
Awesome, thanks.

@danrot as I can see that build task still uses the import/export commands which requires database connection. Also, en and de locales are hardcoded in it. Is it possible to somehow use configured locales there?

**Comment by danrot** [comment]
@sagikazarmark From what I am seeing in https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Bundle/TranslateBundle/Build/TranslationBuilder.php#L23 the locales are already injected, so it should build all given locales. Do you have different code than what I've linked here?

**Comment by wachterjohannes** [comment]
maybe my fork is not up to date (:

**Comment by alexander-schranz** [comment]
as documented `composer create-project` is the right way to start a new project so: *Approach B: Sulu Standard as project template*
