### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by speeeeeed2006** [sulu/sulu-standard#718]
Hello, 

How to redirect http to https, I used the method told by symfony in 
http://symfony.com/doc/current/cookbook/routing/scheme.html
and also in the file security.yml 
but nothing changed. Is there another way to redirect in the code without passing by the virtualHost ?
Thanks .

**Comment by alexander-schranz** [comment]
The link you posted is for the symfony static routes.

if your website is always https you should really configure your webserver vhost correctly.
sulu works correctly on https if it is requested as https. 

it doesnt make sense todo something like this in php as it will cost performance which shouldn't.

So pls edit your vhost. If you cant edit the .htaccess file. And the last step but really not recommended way would be edit the web/website.php and web/admin.php to force https. Because this redirect should be done before initialisation of a kernel.
