### ISSUE TITLE
Sulu favicon in web-root can overwrite project specific favicon

### ISSUE THREAD

**Issue by rs2487** [sulu/sulu-standard#778]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes

#### Actual Behavior

Sometimes IE loads the default favicon from public root folder faster then the favicon which is defined in code. So it is possible that the wrong favicon is display (the sulu one instead of the project specific).

#### Expected Behavior

Allways show favicon which is defined in code.

#### Steps to Reproduce

We had the problem in one of our Zoolu-projects, but i think this is also possible in Sulu.

#### Possible Solutions

Move the Sulu favicon into another folder.

**Comment by alexander-schranz** [comment]
In your project you should just replace the `favicon.ico` in your web folder with the one you want. There are many online tools which uses always `/favicon.ico` to display instead of parse the html. Don't see this as an issue in sulu because its a behaviour of the browser. 

Also as a hint when you have multiple webspaces and you cant copy the favicon and its not always that the favicon is incorrect you should move the favicon include at the top of your `head` IE ignores late definitions of title and favicon inside the head tag.

**Comment by rs2487** [comment]
But, in the case that se sulu favicon was updated, my own will be replaced. I know the chance that this happens is quite small, but we should provide a cms which reduces all possible issues.

**Comment by alexander-schranz** [comment]
Then you will get a conflict when update your sulu and every conflict need to be resolved.

To lock the icon for the sulu backend and show there always the sulu icon I would avoid. I prefer to have the project specific favicon also in the backend, just to know which tab in my browser is which project. But thats my personal opinion. /cc @sulu/core-team

**Comment by wachterjohannes** [comment]
i prefer also the project favicon icon. we would like to go away from sulu-standard and pulling our repository so this shouldnt be any problem then.

**Comment by alexander-schranz** [comment]
Will close this issue. As said the solution for this problem is **moving favicon include at the beginning of your head** and/or 

### replace the sulu `web/favicon.ico` with your own
