### ISSUE TITLE
Differences between standard and minimal edition, wich edition to use for future ?

### ISSUE THREAD

**Issue by AndreFromentalAcelys** [sulu/sulu-standard#792]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | master Standard 

Hi, why there is some differences in structure of standard and minimal edition of Sulu architectures ?

There is for example a var folder with cache, logs and media in minimal edition, but not on standard edition.
There is also adminconsole and websiteconsole files in bin path of minimal edition, but not in standard edition. These files were replaced by app/console and app/webconsole.

I wanna start a project for one of my customer, and I choose Sulu CMF.
I'm interested to use Sulu, but I don't know which edition to choose for a better compatibility with futurs versions of Sulu.

I would like for example to use the companyBundle for futures devs in a stable version.

Should I take a standard or minimal edition ?

Wich version is the most advanced ?

Actually I start without problem devs on minimal, but standard doesn't seems to work.
It's a quite strange ?

Thanks for you helps !

Best Regards,

André

**Comment by alexander-schranz** [comment]
Welcome @AndreFromentalAcelys,

`sulu-minimal` is the way to start a project and as documented in the Getting Started Tutorial here http://docs.sulu.io/en/latest/book/getting-started.html. 

A. The main difference between sulu-minimal and sulu-standard is that we removed the SuluThemeBundle (based on the LiipThemeBundle) in sulu-minimal. 

B. As you did see there are also different Folder structures. This comes from symfony which sulu is based on. Sulu-minimal uses the new folder structure of symfony applications which is also a recommendation to use it.

C. As you see in sulu minimal there is no ClientBundle shipped with because you should create the bundle for your project yourself Symfony Best practice here is create a `src/AppBundle` where the code for your project is (http://symfony.com/doc/current/best_practices/creating-the-project.html#structuring-the-application ). 

D. Consoles where renamed so what is app/console  and app/webconsole in sulu-standard is bin/adminconsole and bin/websiteconsole in sulu minimal to make it more clear that the default console only influence the admin and not the website.

Future updates you normally get over composer update as the most code of sulu is installed over composer from http://github.com/sulu/sulu so features are mostly the same in sulu-minimal and sulu-standard except additional bundles like ThemeBundle which is not really necessary to create also complex projects with different styling. There are mostly only small changes in your project needed mostly documented in the `Upgrade.md` file.

So the recommended way as documented in the docs is definitely choose sulu-minimal. With composer its no problem to add additional bundles to your project like the ThemeBundle, ProductBundle, ....

As you asked the most complex was `sulu-complete` this is deprecated and unmaintained and should not be used anymore. It also had all additional bundles installed by default e.g. SuluProductBundle, SuluSalesBundle, ...

So if you want to install all sulu bundles setup a `sulu-minimal` and add the other bundles like `SuluProductBundle` and co. to it with composer and register them in your AbstractKernel.

**Comment by AndreFromentalAcelys** [comment]
@alexander-schranz Thanks for you response ! I'm better understanding now ! ^^
 It's good to know that.

Have a nice day,
Best regards,

André

**Comment by vmeijer** [comment]
@alexander-schranz  This information is also useful for us, thank you!
