### ISSUE TITLE
Can not save after insert company to contact

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#810]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.5.2

#### Actual Behavior

If you have a contact and add a company, then the save button is disabled.
You need to change something other to enable the save button.

#### Expected Behavior

The save button should be enabled if you add a company.

#### Steps to Reproduce

Open a contact with no company, add a company and try to save contact.

**Comment by danrot** [comment]
Are you talking about the "Organisation" from the following screenshot:

![image](https://cloud.githubusercontent.com/assets/405874/25038368/d4bf40a0-20fe-11e7-9ac5-47f385c67057.png)

Because I just tested it, and it works flawlessly in `develop` (and I cannot imagine any changes there changing that behavior).
