### ISSUE TITLE
Test microdata on page with LivePreview throws errors

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/sulu-standard#813]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 1.5.3

#### Actual Behavior

If you have a website with LivePreview in sulu admin and if you would test this page on https://search.google.com/structured-data/testing-tool then you will receive many errors.

A solution to remove this errors is to check on each property if page is in preview-mode or not. But this is not the way to go i think.

#### Expected Behavior

There should be a better way to solve the errors with microdatas.

#### Steps to Reproduce

Create a page with live preview elements, open the [testing tool of google](https://search.google.com/structured-data/testing-tool, insert the url (or code) and run the test. 
You will see same errors.

![bildschirmfoto 2017-04-10 um 10 17 05](https://cloud.githubusercontent.com/assets/8446518/24852201/f70e4884-1dd6-11e7-8ab4-0708f5331186.png)

**Comment by danrot** [comment]
I think the usage of these properties don't make too much sense, since we always render the entire content block anyway. The properties are only used to extract the data from the completely rendered block. There are probably more efficient and less error-prone ways to do this.

What comes to mind is to simply remove these property attributes, and do a diff between the representations (which is actually only "necessary"  to reduce the traffic).

That being said, I don't think we can change anything about that before 2.0.

**Comment by danrot** [comment]
That's also related to https://github.com/sulu/sulu/issues/3175. I am only keeping the other issue, since it is in the correct repository.
