### ISSUE TITLE
How to hide subpages from front-end

### ISSUE THREAD

**Issue by ilyasavitski** [sulu/sulu-standard#826]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

How can i prevent some subpages from being available in fron-end?
And i need to make the pages not available in search results. Is it possible?

**Comment by wachterjohannes** [comment]
what do you mean with hiding? You can mark them as not published in the backend and they wont be accessible over the website.

**Comment by ilyasavitski** [comment]
I have page template "product". All the products pages are subpages of the page "Products". But i don't need to have a single page for every product cause all of them shown on their parent page.

You can check it [here](http://lamyra.org/en/products).

**Comment by thomasduenser** [comment]
Hello @ilyasavitski - if your page "Products" has only the information of the subpages, why is "product" an own page template?

Maybe you could simply add [the Content Type Block](http://docs.sulu.io/en/latest/reference/content-types/block.html) to your "Products" page template or create a snippet for each product (instead of a page) and include them with the [Snippet Content Type](http://docs.sulu.io/en/latest/reference/content-types/snippet.html).

Snippets have no URL, which means they are not accessible.

**Comment by wachterjohannes** [comment]
@ilyasavitski @thomasduenser is completely right :) you should switch to snippets in mine opinion - they dont have a URL and can be allocated inside other pages. if you need them inside the page tree (structuring reasons for example) you can use a custom controller (in the template XML) in your AppBundle which throws a 404 exception.

**Comment by danrot** [comment]
@ilyasavitski I guess your issue is solved with these two answer, so I am closing that issue.
