### ISSUE TITLE
Smart Content Admin Sort Order is wrong when including Sub Folders

### ISSUE THREAD

**Issue by ampaze** [sulu/sulu-standard#840]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.6.13

#### Actual Behavior

When configuring a Smart Content to include Sub Folders and using the Admin Sort Order the order is only determined by the pages and not by the parent folders.

This means that the pages are ordered seemingly random instead of the way they where ordered in the Pages Tree View.

![screenshot 2018-02-02 15 49 15](https://user-images.githubusercontent.com/758593/35739008-a811bb5e-0830-11e8-98ee-9984deee6101.png)

#### Expected Behavior

The sort order of the parent folders should be considered when determining the order of the pages, at least if Admin Order is wanted. That way the order is the same as in the Pages Tree View.

#### Steps to Reproduce

Configure a Smart Content to include Sub Folders and using the Admin Sort Order and look at the list.

**Comment by danrot** [comment]
We were experiencing the same issue, but the problem here is that it is not clear what the resulting order should be. Someone could also argue that he'd like the top pages be first and order level by level afterwards.

For us it doesn't really make sense to have it ordered based on the admin if you have multiple folders, since the order is only meant to be applied in a list. So we were thinking about removing this Admin sort order option as soon as you are loading pages from multiple folders.

And in your special case it might make sense to order them by some date, doesn't it?

**Comment by ampaze** [comment]
Thanks for the reply,

I would still consider the admin order to be exactly the one that is seen in the pages tree view, including the position of sub folders, which are also pages anyway. Top pages first and folders after that is something different to the admin order. Why is the admin order only meant to be applied in a list, when it is available and used to sort pages in the navigation for example.

In my special case the created at date is not always the order that is wanted, hence using the manual order. If I would be able to order by a page content date field, this would be another story though.

**Comment by danrot** [comment]
The admin order can't be what it is in the pages tree view, since the representation is completely different. Whatever sorting order we would choose in that moment is not how it is when it is displayed in a tree/column view.

If you have a tree like this:

```
Page 1
- Page 1.1
- Page 1.2
Page 2
- Page 2.1
```

Then you have two different versions how to sort that with the admin order in a list, which both are totally acceptable:

```
- Page 1
- Page 1.1
- Page 1.2
- Page 2
- Page 2.1
```

And the other possible order:

```
- Page 1
- Page 2
- Page 1.1
- Page 1.2
- Page 2.1
```

The only way I see that we can solve that, is to remove the `Admin order` and introduce two others for both different versions.

**Comment by ampaze** [comment]
I would be fine with two admin order options, although I am not sure what to call the second one :)

**Comment by danrot** [comment]
Yeah, and the other thing is if we can get these versions in a performant way. And to be honest this issue does not have a high priority for us, and we do not have any resources left to work on it currently. Could you imagine fixing this on your own and submitting a PR?

**Comment by ampaze** [comment]
Fair enough. 
I am not sure I could fix this within a reasonable amount of time, as the sorting mechanisms seems to be very reliant on looking at single pages only, e.g. without the hierarchy.

**Comment by danrot** [comment]
This is actually related to https://github.com/sulu/sulu/issues/5017, and the other repo is the correct one to have this issue. Therefore going to close this one.
